### ISSUE TITLE
Failed to download bundle

### ISSUE THREAD

**Issue by Daemach** [cfsimplicity/spreadsheet-cfml#267]
I'm suddenly getting this error when trying to start my app.  Did something change?

ERROR: Failed to download the bundle for [spreadsheet-cfml] in version [5.1.0.0] from [http://release.lucee.org/rest/update/provider/download/spreadsheet-cfml/5.1.0.0/?webId=75f39783e2acd6c240160d494da5d9fa&webSecurityKey=dda350cc-d098-40c9-b1f2-b3615cdc858d&serverId=5cb0e071492bb06d3ad76648cbb58261&serverSecurityKey=c5561f4c-252f-46a1-bd42-e1b8c4761a4d&allowRedirect=true&jv=11.0.12], please download manually and copy to [D:\Commandbox\server\6E02596F87A5CCFF8715D3CC5A2F1CEE-mars_integration\lucee-5.3.8.206\WEB-INF\lucee-server\bundles]

**Comment by cfsimplicity** [comment]
I assume you've upgraded to the latest release v3.1.0 and that does include a new OSGi bundle v5.1.0.0.

But the bundle is included in the package so I don't know why Lucee/Commandbox is trying to download it as if it were an extension.

A server restart shouldn't be needed, but I would try that.

**Comment by cfsimplicity** [comment]
Any luck? I've run the latest version in both Tomcat and CommandBox instances and not seeing any error. Wondering if it's to do with how you upgraded perhaps?

**Comment by Daemach** [comment]
Server restart fixed it.  Thanks!
