### ISSUE TITLE
Feature Request: Spreadsheet Read rows/cols range start -> unknown end

### ISSUE THREAD

**Issue by scottsteinbeck** [cfsimplicity/spreadsheet-cfml#268]
```
spreadsheet.read( src=filepath, format="query", columns="14-", rows="4-");
```
I would like to specify a start point with the end being unknown. I have spreadsheets that include sheet information (title, date, sheet description, accounting codes, etc.) that is not part of the actual data that needs to be imported.

Currently, I'm just picking an arbitrarily large number as the end to make it work like rows="4-10000" but since the library automatically finds the end if I don't pick anything, I am hoping the option above may be possible!

**Comment by cfsimplicity** [comment]
Nice suggestion, Scott. Can you please try it out with the latest `develop` branch and let me know if it's working? If not, please re-open the ticket.

**Comment by scottsteinbeck** [comment]
Sweet, ill try it now

**Comment by scottsteinbeck** [comment]
Looks like the columns are working correctly, however, the rows only pull back the first 10 or so records.

**Comment by scottsteinbeck** [comment]
```
sheetQry = spreadsheet.read( src=filepath, sheetNumber=1, format="query", columns="12-", rows="4-", columnnames=columnnames.toList());
```

![Screen Shot 2021-11-23 at 9 13 41 AM](https://user-images.githubusercontent.com/5215594/143071938-13e6902a-286c-410d-b313-6b297047f3b7.png)

**Comment by cfsimplicity** [comment]
Strange, I'm getting all expected rows in my tests.

Any chance you could attach the spreadsheet file you're reading from so I can work with it? Or a sanitized/simplified version if it's sensitive.

**Comment by scottsteinbeck** [comment]
I think its due to some of the rows are hidden

**Comment by cfsimplicity** [comment]
Thanks. Hidden rows should be included by default, but blank rows aren't. You can specify `includeBlankRows=true`.

**Comment by cfsimplicity** [comment]
Ah I see what you mean, the hidden rows might be affecting what calculated as the "last" row.

**Comment by scottsteinbeck** [comment]
If you still want my test file I can email it to you.

**Comment by cfsimplicity** [comment]
Yes please. I think you can just drop it onto a comment here to attach.

**Comment by scottsteinbeck** [comment]
[testsheet.xls](https://github.com/cfsimplicity/spreadsheet-cfml/files/7590120/testsheet.xls)

**Comment by cfsimplicity** [comment]
Thanks. What would be your `read()` call and what would you expect it to return from that particular file?

**Comment by cfsimplicity** [comment]
I don't have your `columnnames` variable, but leaving that out I'm getting 1677 rows... Is that not right?

![Screenshot 2021-11-23 at 18-05-23 https test](https://user-images.githubusercontent.com/456718/143080071-720aabe5-c024-44b9-9320-61907fcbf7eb.png)

**Comment by scottsteinbeck** [comment]
Wierd, i cant explain it, but its working now

**Comment by cfsimplicity** [comment]
No worries, Scott. Glad it's working.
