### ISSUE TITLE
Add Sponsor link

### ISSUE THREAD

**Issue by michaelborn** [cfsimplicity/spreadsheet-cfml#270]
This library is too awesome not to have a Sponsor link, just letting you know. :smile:

**Comment by cfsimplicity** [comment]
Ha! Thanks Michael. Wasn't aware of the sponsor stuff on Github. So far I've been doing it purely for the love of CFML, but I'll give it some thought.

**Comment by cfsimplicity** [comment]
https://github.com/sponsors/cfsimplicity
