### ISSUE TITLE
Instantiation errors on ACF 2016

### ISSUE THREAD

**Issue by GaryStanton** [cfsimplicity/spreadsheet-cfml#271]
I've just tried running your awesome project on ACF2016 for the first time and found a couple of issues that were stopping it instantiating.
They're syntax related, so I suspect this is specific to 2016, and possibly even the update level I'm on - however they're easy fixes so if you wouldn't mind, I'll submit a PR?

In the row.cfc file in helpers, it was erroring on the `cfloop` call in `populateFromArray`, saying that 'array' is not a valid attribute. Not sure why, but changing that to a for-in loop has fixed it.
Secondly there's an elvis operator in `format.cfc` in the function `addCellStyleToFormatMethodArgsIfStyleOverwriteAllowed`, which was returning null for `arguments.workbook`. I've heard there are known bugs with ACF and elvis operators, but I don't tend to use them myself. Either way, changing it to a ternary `structKeyExists` check has resolved for me.

**Comment by cfsimplicity** [comment]
Hi Gary

Which Update level of ACF2016 are you on? The test suite includes tests that call on that code and I'm not seeing any problems running update 17 via CommandBox.

According to CFDocs, `cfloop` with an array was introduced in ACF8, and the elvis operator in ACF11 so the syntax is definitely supported and appears to be working fine in isolation:

https://trycf.com/gist/51fbbcd08aa60381c30deb7a2836701f/acf2016?theme=monokai

The advantage of `cfloop` over `for-in` here is that both the `item` and `index` variables are auto-managed.

Elvis operators are incredibly useful and are used in many places in the library. 

To be honest I'd rather not have to "polyfill" them for the sake of a buggy ACF point release that has a patch. Support for a particular engine version really means the most recent stable patched release.

**Comment by GaryStanton** [comment]
Yeah, I thought you might have reservations about making those changes - that's why I wanted to post it as an issue first.  ;)
The version I'm running here is update 4 - very old! (It's just an intranet, no outside access.)
Your test failed here too, so it seems likely an update will fix. I'll see if I can get that done and get back to you if it's still failing afterward... I suspect it'll be fine.  
Thanks.
