### ISSUE TITLE
Read() not importing trailing empty columns

### ISSUE THREAD

**Issue by Daemach** [cfsimplicity/spreadsheet-cfml#272]
I have a spreadsheet template for financial information where not all columns/fields are required.  I found yesterday that any blank column past the last column with data in it did not show up in the query.   Moving those two columns to the beginning, so the last column had data imported them all, blanks included which is fine.  I can deal with blank data, but missing column names are a pain.  Is there a way to get around this?  I was using the read() method and all I saw was a flag regarding hidden columns.

**Comment by cfsimplicity** [comment]
Yes, I can replicate that and it's definitely a bug. If you specify a header row when reading a sheet then each header value should result in a query column regardless of whether the result of the column contains any values.

Thanks for reporting.

Fix coming right up....

**Comment by cfsimplicity** [comment]
Please could you test with `develop` and re-open if it's not working as you expect. Thanks.
