### ISSUE TITLE
formatRows() errors if range specified is a single row

### ISSUE THREAD

**Issue by arjanmuthert** [cfsimplicity/spreadsheet-cfml#280]
The formatRows function calls the function formatRow  (row 971) with the variable "style". 
This gives an error "variable [style] doesn't exist"
I think "style" should be "arguments.cellStyle"

Version: main / develop v3.2.3

**Comment by cfsimplicity** [comment]
Yes, that error is thrown if there's only 1 row in the range. That condition isn't actually unnecessary. 

Thanks for reporting. Fix coming up.
