### ISSUE TITLE
Can't import spreadsheet

### ISSUE THREAD

**Issue by Daemach** [cfsimplicity/spreadsheet-cfml#284]
I'm trying to import the attached spreadsheet and it's failing for some reason.  Often, if I inspect a spreadsheet and remove all extraneous data, it starts working (it would be great if this wasn't necessary).  This time it's not working.  Can you take a look?

```
  function importSpreadSheet( path, header = true, tab ) {
    var tabName = arguments.tab;
    switch ( listLast( path, "." ) ) {
      case "xls":
      case "xlsx":
        var args = { src : path, format : "query" }
        if ( arguments.header ) {
          args.headerRow = 1
        }
        if ( !isNull( arguments.tab ) ) {
          var info       = spreadsheet.info( path )
          args.sheetName = listToArray( info.sheetnames ).filter( ( e ) => e contains tabName )[ 1 ]
        }
        return spreadsheet.read( argumentcollection = args );
        break;
      case "csv":
        return spreadsheet.csvToQuery( filepath = path, firstRowIsHeader = header );
        break;
    }
  }
```

[Holdings_Template_allValidXLSX.xlsx](https://github.com/cfsimplicity/spreadsheet-cfml/files/8155571/Holdings_Template_allValidXLSX.xlsx)

**Comment by cfsimplicity** [comment]
Calling your function with
```
path = ExpandPath( "Holdings_Template_allValidXLSX.xlsx" )
dump( importSpreadSheet( path ) )
```
seems to work fine for me on Lucee 5.3.8.206

![Screenshot 2022-02-28 at 18-14-28 https test](https://user-images.githubusercontent.com/456718/156036045-c8d41dd8-43b6-46fd-afa2-eba51f1faf58.png)

How is it failing for you?

**Comment by Daemach** [comment]
I think something was wrong with the server.  It worked locally, I updated the libraries, restarted the services and it's working now.  Sorry to waste your time on this.

The extra info thing is still a problem, though.  Unfortunately, I don't have an example sheet to send you.  I'll open another case when I get one.
