### ISSUE TITLE
OSGI bundle error

### ISSUE THREAD

**Issue by Daemach** [cfsimplicity/spreadsheet-cfml#289]
I occasionally get the following error when trying to use cfml-spreadsheet.  I don't know what causes it, but it requires a service restart to clear.

**Comment by cfsimplicity** [comment]
Did you upload the right screenshot? Not seeing any OSGi bundle error there or anything to do with the library??

**Comment by cfsimplicity** [comment]
If you are getting OSGi errors with the library, particularly after upgrading, try calling this method:
```
spreadsheet.flushOsgiBundle()
```

**Comment by Daemach** [comment]
Bah - no, this is the correct one.  I wonder if that could go in a try/catch in the library itself?

![image](https://user-images.githubusercontent.com/12553953/158465906-5b8aa0c6-771c-42f1-9b14-d8ed2b551ae8.png)

**Comment by cfsimplicity** [comment]
Possibly. Let me give it some thought.

**Comment by cfsimplicity** [comment]
OK, that's done. I'm not sure why it happens as when a new bundle version is requested it should just be loaded alongside the previous one. But I have seen that error myself when upgrading, hence the flushing method.

The condition should be caught now. Difficult to auto-test, but I did a dummy bundle version upgrade and tested manually and it no longer errored.
