### ISSUE TITLE
DataValidation & dropdown

### ISSUE THREAD

**Issue by ivanionut** [cfsimplicity/spreadsheet-cfml#300]
hi,
is it possible to implement [this class](https://poi.apache.org/apidocs/dev/org/apache/poi/ss/usermodel/DataValidation.html) in spreadsheet-cfml to have the ability to generate dropdown?

thanks,
Ivan

**Comment by ivanionut** [comment]
hi Julian,
what I want to do are "_simple_" drop-downs list within a cell or column.

Like this: https://support.microsoft.com/en-us/office/create-a-drop-down-list-7693307a-59ef-400a-b769-c5402dce407b

**Comment by cfsimplicity** [comment]
Hi Ivan

I've added support for data validations to the develop branch. Could you please download and test it?

Basic usage is as follows:

```
myWorkbook = spreadsheet.newXlsx();
dv = spreadsheet.newDataValidation()
  .onCells( "A1:C1" );
  .withValues( [ "New York", "London", "Paris" ] ) //an array of valid values
  .addToWorkbook( myWorkbook );
```
Pulling the values from other cells in the workbook is also supported:
```
myWorkbook = spreadsheet.newXlsx();
dv = spreadsheet.newDataValidation()
  .onCells( "A1:C1" );
  .withValuesFromSheetName( "cities" )
  .withValuesFromCells( "A1:A3" )
  .addToWorkbook( myWorkbook );
```
I'll create full documentation when on release but meantime [the tests](https://github.com/cfsimplicity/spreadsheet-cfml/blob/develop/test/specs/dataValidation.cfm) provide a bit more detail.

Please let me know if you find any problems or have questions.

**Comment by ivanionut** [comment]
@cfsimplicity wow, thanks! it works very well!

**Comment by cfsimplicity** [comment]
OK, great. I'll cut a new release soon.
