### ISSUE TITLE
writeToCsv() doesn't support the workbook column datatypes

### ISSUE THREAD

**Issue by garciadev** [cfsimplicity/spreadsheet-cfml#313]
The writeToCsv function doesn't support the workbook column datatypes. In my case, I have a date properly formatted as `yyyy-mm-dd`, but when it generates the CSV, `queryToArrayForCsv()` in csv.cfc detects the value as a date, and then formats it as datetime. It would be good to allow a format to be specified instead, and then default to datetime if nothing is passed in.

**Comment by cfsimplicity** [comment]
Hi Daniel. I'll have a think about this. Specifying data types is normally only applicable when passing data into a workbook.

I can't remember exactly why `queryToArrayForCsv()` forces the datetime format even if the value is a string. Perhaps the solution is that it should respect the cell type regardless. But you could work around the current behaviour by overriding the default `datetime` format to make it date only just for this operation:

```
Spreadsheet = New spreadsheet.SpreadSheet( dateFormats: { DATETIME: "yyyy-mm-dd" } )
data = QueryNew( "date", "VarChar", [ "2002-01-01" ] )
wb = spreadsheet.newXlsx()
spreadsheet
  .addRows( wb, data )
  .writeToCsv( wb, "c:/temp/test.csv", true )
```

**Comment by garciadev** [comment]
In my case, I am first creating a workbook using spreadsheet.workbookFromQuery() where I pass in the data and datatypes. After I have that, if the file extension is .csv, I call spreadsheet.writeToCsv(), else I call spreadsheet.write().

**Comment by cfsimplicity** [comment]
How you create the workbook doesn't matter. The issue is with `writeToCsv()`. But as I say you should be able to control the format of your date value when written to the csv file by overriding `dateFormats.DATETIME`.

**Comment by cfsimplicity** [comment]
I've changed the csv handling so that it will no longer mess with date strings (i.e. a VarChar value formatted as a date). This should solve your issue without you having to override the DATETIME format.
