### ISSUE TITLE
Add function to automatically create URL, email & file links

### ISSUE THREAD

**Issue by JamoCA** [cfsimplicity/spreadsheet-cfml#316]
I'm exporting a column of URLs and would like them to be clickable.  I'm currently using `newStreamingXlsx` and `addRows` to populate the table with a header and defined datatypes.  I'm able to generate clickable links by looping over the query after all rows have been added.

```cfml
for (row in myQuery){
	if (isvalid("url", row.link)){
		spreadsheet.setCellHyperLink(workbook, row. Link, myQuery.currentrow+1, linkColumnPosition);
	}
}
```

I was wondering if `setCellHyperlink` could be integrated with new datatypes like `URL`, `Email`, `File` where values are formatted as `string` and then automatically set using `setCellHyperLink` if length (or valid) using the cell's value as the link.  This would allow the links to be created when `addRows` is performed instead of a separate routine.  (If this isn't a good idea, perhaps a new function to perform this function to an entire column if the cell's value has length or is valid.)  Thoughts?

**Comment by cfsimplicity** [comment]
Great suggestion, James!

**Comment by JamoCA** [comment]
It appears to work perfectly.  I tested by added an email column to my initial script, added valid & bogus email address strings, removed the now-deprecated logic (for the links) and all populated + validated cell values were correctly hyperlinked.

Thanks!

**Comment by cfsimplicity** [comment]
I can replicate that in Lucee too. Let's treat this as a [new separate issue](https://github.com/cfsimplicity/spreadsheet-cfml/issues/322).
