### ISSUE TITLE
Some values are not converted to hyperlinks when using URL datatype

### ISSUE THREAD

**Issue by cfsimplicity** [cfsimplicity/spreadsheet-cfml#322]
I'm encountering an issue (using CF2016 or CF2021) where not all URL datatypes are being converted to links. I've extended your example to include 3 additional columns with the same exact URL value and the even columns (urls2 & urls4) aren't converting to hyperlinks.

```
spreadsheet = new luceeSpreadsheet.Spreadsheet();
workbook = spreadsheet.newStreamingXlsx();

testUri = "https://w3c.org";
testEmail = "test@test.com";
testFilePath = "test.xlsx";
data = QueryNew( "urls,urls2,urls3,urls4,emails,files", "VarChar,VarChar,VarChar,VarChar,VarChar,VarChar", [ [ testUri, testUri, testUri, testUri, testEmail, testFilePath ] ] );
datatypes = { url: [ "urls", "urls2", "urls3", "urls4" ], email: [ "emails" ], file: [ "files" ] };
spreadsheet.addRows( workbook=workbook, data=data, datatypes=datatypes, includeQueryColumnNames=true ).download(workbook, "test_#datetimeformat(now(), 'yyyymmddHHnnss')#.xlsx");
```

![image](https://user-images.githubusercontent.com/1112671/234304054-712be302-20dd-4692-8aea-807c8e9d24ba.png)

_Originally posted by @JamoCA in https://github.com/cfsimplicity/spreadsheet-cfml/issues/316#issuecomment-1521864134_

**Comment by cfsimplicity** [comment]
Found and (hopefully) fixed. Please could you check using the latest `develop` branch? Thanks.

**Comment by JamoCA** [comment]
I've tested it in production against a larger set of data and it is correctly creating clickable links for all `url`, `mail` and `file` datatypes.
