### ISSUE TITLE
Library should default to returning cached cell formula values instead of always recalculating

### ISSUE THREAD

**Issue by cfsimplicity** [cfsimplicity/spreadsheet-cfml#359]
See #358 

There is now a `setReturnCachedFormulaValues()` switch to control this but it defaults to false currently. Defaulting to `true` is best though as it is clearly more performant, and avoids formula evaluation issues (sometimes POI cannot handle formulas that work fine in Excel).

This is a potentially breaking change though so only implement at the next major release.

**Comment by Daemach** [comment]
Has this change been merged into production?  I did a full reinstall today and I'm getting the following error with 3.12.0

`component [modules.spreadsheet-cfml.Spreadsheet] has no function with name [setReturnCachedFormulaValues]`

**Comment by cfsimplicity** [comment]
No, as you'll see from the labels this is a breaking change that will be released in version 4.0. Hopefully coming soon.

**Comment by Daemach** [comment]
Did anything major change, especially java-related, in the dev branch around 2/9? I downloaded that when you asked me to test the  `setReturnCachedFormulaValues` functionality.

Spreadsheet-cfml no longer works with the Pusher java components.  We're trying to figure out where the conflict is now, but if I comment out pusher, spreadsheets work fine.  If I comment out spreadsheets, pusher runs fine.  Together we get bizarre messages such as the one below. 
![image](https://github.com/cfsimplicity/spreadsheet-cfml/assets/12553953/11312edb-14ef-4282-b087-2372788f9425)
![image](https://github.com/cfsimplicity/spreadsheet-cfml/assets/12553953/9e26086b-9fb1-40a2-820e-78b153da0c92)

**Comment by cfsimplicity** [comment]
No, there were only minor code changes between the 3.12.0 release (November) and the develop version on 9 Feb. No lib/dependency changes. 

I'm not familiar with Pusher I'm afraid.

Are you trying to use the 4.0 version of the spreadsheet lib just released?

**Comment by Daemach** [comment]
I didn't know it was released...  We will try that next.

https://pusher.com/
https://github.com/pusher/pusher-websocket-java
