### ISSUE TITLE
CI is crashing, can't find testbox

### ISSUE THREAD

**Issue by zspitzer** [cfsimplicity/spreadsheet-cfml#368]
@cfsimplicity a good GHA debugging trick is to to dump out the working dir as an artifact

https://github.com/lucee/lucee-testlab/blob/main/.github/workflows/spreadsheet-cfml.yml#L27

`if: always()` is also useful, if things are crashing, it means it always runs (not the case here)

**Comment by cfsimplicity** [comment]
Apologies, I found a rookie error in my tests: used mixed case for a variable used in test file paths which should have been lower case. Fixed and now Lucee at least is passing.

ACF 2021 and 2023 still failing I'm pretty sure because the image package needs installing.

**Comment by cfsimplicity** [comment]
https://github.com/cfsimplicity/spreadsheet-cfml/commit/92b874dc8f795f467d6898ed5d62f7d757d59a46
https://github.com/cfsimplicity/spreadsheet-cfml/commit/ab54fe1d9d7fa4a2f1952070fdc2a0641bbecb86
https://github.com/cfsimplicity/spreadsheet-cfml/commit/3adaf500d37cab2dcda49f1b1acfa1e76f7e144b

**Comment by cfsimplicity** [comment]
CI succeeding again on all engines.

https://github.com/cfsimplicity/spreadsheet-cfml/actions/runs/9462945259
