### ISSUE TITLE
Create sheet at specific position

### ISSUE THREAD

**Issue by tgmweb** [cfsimplicity/spreadsheet-cfml#369]
The apache POI createSheet method includes an option position of the sheet in the workbook: 

`createSheet(XSSFWorkbook book, String nameSheet, Integer positionSheet)`

The third argument in this moduled is "overwrite" instead. Is there a way of creating a sheet in a specific position, or moving the sheets around once they're added?

**Comment by tgmweb** [comment]
My bad, I misread a SO article which is what you suggested; a helper method to reorder the sheets once created. This is perfect and enough for me!

https://stackoverflow.com/questions/16626401/ordering-of-sheets-in-excel-in-apache-poi

**Comment by cfsimplicity** [comment]
As I say, helper methods aren't supported, so it might change or be removed in the future. OK for now as a workaround to do what you're looking for, but I will create a new supported `moveSheet()` method as part of the public API in the next release.
