### ISSUE TITLE
v3.12.0 error with streamingXml due to non-existent user "poifiles" sub-directory

### ISSUE THREAD

**Issue by JamoCA** [cfsimplicity/spreadsheet-cfml#382]
When using CF2016 w/v3.12.0 and using StreamingXml (using either the `newStreamingXlsx` or `new` methods), CF returns a "java.nio.file.NoSuchFileException" error when trying to access a temporary XML file in a non-existent "\AppData\Local\Temp\poifiles" directory.

I know that this project has moved on to v4 and now only supports CF2018+, but was wondering what may be causing this error and whether it may also exist in v4.

I tried searching the 3.12.0 library source for "poifiles" and no results were returned.

**SOLUTION:** I manually created a "poifiles" sub-directory in the user's "AppData\Temp" path (which was missing) and it now works. (I'm sharing here in case it may benefit other developers.)

**Comment by cfsimplicity** [comment]
Looks like an internal java or POI error specific to your local environment. Permissions, maybe? Sorry not really sure.

Thanks for posting the workaround anyway.

**Comment by JamoCA** [comment]
We're guessing that the directory may have been deleted during a Windows "delete temp files" operation after ColdFusion Server had been started and the POI library was used.

I found a potential workaround on [StackOverflow](https://stackoverflow.com/a/5324534), but it requires setting `java.io.tmpdir` to a directory with permissions.

I'm not sure if changing this directory means that a separate process would need to delete orphaned temp files, but 6+ year old `poi-sxssf-sheetxxxx.xml` files are still undeleted in our user's "poifiles" temp directory so it may not be currently automatically deleted anyway. (This approach also may also require routine deletion of temp files & directories.)

```
system = createobject("java", "java.lang.System");
system.setProperty("java.io.tmpdir", "C:\myJavaTempDirectory\");
```

**QUESTION:** Any interest in extending the configuration to allow changing default settings using the [Apache POI TempFile](https://poi.apache.org/apidocs/org/apache/poi/util/TempFile.html) and [DefaultTempFileCreationStrategy](https://poi.apache.org/apidocs/org/apache/poi/util/DefaultTempFileCreationStrategy.html) helper classes?

```
File dir = new File("somepath");
dir.mkdir();
TempFile.setTempFileCreationStrategy(new DefaultTempFileCreationStrategy(dir));
```
